### ISSUE TITLE
Only displays for a moment?

### ISSUE THREAD

**Issue by dankegel** [qwertzui11/cef_osr#1]
Tried this with ubuntu 14.04 and cef 2272.2077.
Got ogre with

  sudo apt-get libogre-1.8-dev
  cat > plugins.cfg <<EOF
PluginFolder=/usr/lib/x86_64-linux-gnu/OGRE-1.8.0
Plugin=RenderSystem_GL.so
Plugin=Plugin_OctreeSceneManager.so
EOF

Had to adjust FindCef3.cmake a bit

It displays for about a half a second; after that, it gives up and just shows a blank window.
2nd run it doesn't display anything.

**Comment by qwertzui11** [comment]
could u please post the logs, Should be called ogre.log and cef.log, or something like that.
I tested the demo with ogre1.9 - if the logs r clean, could u try with ogre1.9?

**Comment by dankegel** [comment]
Same symptoms with 1.9.
Here's some of the console output:

Particle Renderer Type 'billboard' registered
SceneManagerFactory for type 'OctreeSceneManager' registered.
[New Thread 0x7fffcc364700 (LWP 55650)]
[New Thread 0x7fffcbaba700 (LWP 55653)]
[Thread 0x7fffcbaba700 (LWP 55653) exited]
Exception thrown during bootstrapping
Extension or internal compilation error.
Program received signal SIGPIPE, Broken pipe.
(gdb) bt
#0  0x00007ffff2cc288d in write () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff55b1eb1 in IPC::ChannelPosix::ProcessOutgoingMessages() () from /opt/foobar/deps-64-10/cef2272/Release/cefclient/libcef.so
#2  0x00007ffff55b21ca in IPC::ChannelPosix::Send(IPC::Message*) () from /opt/foobar/deps-64-10/cef2272/Release/cefclient/libcef.so

Evidently v8 is unhappy.  Might be my funny install of cef 2077, who knows.  I guess the next step would be for me to write a full repro script.

**Comment by qwertzui11** [comment]
There should be several actual, way more detailed, log FILES?

**Comment by dankegel** [comment]
Here's Ogre.log:
https://gist.github.com/dankegel/b15f2b3ff4bb029714d3

**Comment by qwertzui11** [comment]
- maybe u mixed up some lib-versions of cef?
- Pls ensure u got all needed files (*.pak, locales, icudtl.dat) accessible for ur application.
- try another cef version (in Debug)
- ask the same question in the official forum http://www.magpcss.org/ceforum maybe there someone has seen the error before

**Comment by qwertzui11** [comment]
Because there seem to be no further questions, I'm closing this issue - please reopen if that's not the case.
